import { Product, Category, Coupon, Banner } from '../types';

export const initialCategories: Category[] = [
  {
    id: 'womens-fashion',
    name: "Women's Fashion",
    slug: 'womens-fashion',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    description: 'Stitched lawn, chic pret kurtis, embroidered festive sets and dupattas.',
    itemCount: 4,
  },
  {
    id: 'mens-apparel',
    name: "Men's Apparel",
    slug: 'mens-apparel',
    image: 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=600&auto=format&fit=crop&q=80',
    description: 'Classic embroidered kurtas, formal shirts, and wash & wear unstitched suits.',
    itemCount: 4,
  },
  {
    id: 'footwear-chappal',
    name: 'Footwear & Chappal',
    slug: 'footwear-chappal',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    description: 'Authentic handcrafted Peshawari chappals, Multani khussas, and leather shoes.',
    itemCount: 3,
  },
  {
    id: 'leather-accessories',
    name: 'Leather & Accessories',
    slug: 'leather-accessories',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
    description: 'Full-grain cowhide wallets, messenger laptop bags, and belts.',
    itemCount: 3,
  },
  {
    id: 'electronics-audio',
    name: 'Electronics & Audio',
    slug: 'electronics-audio',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    description: 'High-fidelity active noise-cancelling earbuds, smartwatches, and chargers.',
    itemCount: 2,
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-001',
    name: "Women's 3-Piece Stitched Digital Printed Lawn Suit",
    slug: 'womens-3pc-digital-printed-lawn-suit',
    description: 'Premium grade breathable summer lawn collection featuring intricate digital floral patterns with an embroidered neckline, matching dyed cambric trousers, and a lightweight printed chiffon dupatta.',
    category: "Women's Fashion",
    price: 4950,
    salePrice: 3850,
    stock: 24,
    sku: 'SHN-WMN-L01',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Emerald Teal', 'Rose Quartz', 'Royal Indigo'],
    tags: ['Lawn', 'Stitched', 'Festive', 'Best Seller'],
    featured: true,
    isNew: true,
    isActive: true,
    specifications: {
      Fabric: '100% Super Combed Lawn 80/80',
      Dupatta: 'Printed Pure Voile Chiffon (2.5m)',
      Trouser: 'Solid Dyed Cambric Cotton',
      Stitching: 'Tailored Overlocked with Lace Hem detailing',
      Care: 'Machine wash delicate or hand wash cold',
    },
  },
  {
    id: 'prod-002',
    name: 'Traditional Handcrafted Peshawari Chappal (Pure Leather)',
    slug: 'handcrafted-peshawari-chappal-leather',
    description: 'Timeless handmade Peshawari Chappal crafted by veteran artisans using 100% top-grain buffalo leather, tyre rubber sole for lifetime durability, and signature hand-stitched border.',
    category: 'Footwear & Chappal',
    price: 3499,
    salePrice: 2899,
    stock: 18,
    sku: 'SHN-FTW-P02',
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['40 (7)', '41 (8)', '42 (9)', '43 (10)', '44 (11)'],
    colors: ['Mustard Brown', 'Jet Black', 'Deep Tan'],
    tags: ['Peshawari', 'Traditional', 'Leather', 'Handmade'],
    featured: true,
    isNew: false,
    isActive: true,
    specifications: {
      Material: '100% Genuine Full-Grain Leather Upper & Insole',
      Sole: 'Recycled Aircraft Tire Rubber (Non-slip)',
      Stitching: 'Heavy Duty Waxed Thread Hand-stitching',
      Origin: 'Charsadda / Peshawar, Pakistan',
    },
  },
  {
    id: 'prod-003',
    name: "Men's Luxury Embroidered Cotton Kurta (Self-Jacquard)",
    slug: 'mens-luxury-embroidered-cotton-kurta',
    description: 'Elevated formal menswear tailored from premium Egyptian self-textured jacquard cotton with understated tone-on-tone ban collar embroidery and branded metal buttons.',
    category: "Men's Apparel",
    price: 3890,
    salePrice: 3190,
    stock: 30,
    sku: 'SHN-MEN-K03',
    images: [
      'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['S (38)', 'M (40)', 'L (42)', 'XL (44)'],
    colors: ['Ivory Cream', 'Navy Charcoal', 'Pistachio Mint'],
    tags: ['Kurta', 'Eid Collection', 'Menswear', 'Cotton'],
    featured: true,
    isNew: true,
    isActive: true,
    specifications: {
      Fabric: '100% Fine Long-Staple Combed Jacquard Cotton',
      Collar: 'Classic Mandarin Ban Collar with Threadwork',
      Fit: 'Smart Regular Fit',
      Pockets: 'Two Deep Concealed Side Pockets',
    },
  },
  {
    id: 'prod-004',
    name: 'Top-Grain Vintage Hunter Leather Bifold Wallet',
    slug: 'top-grain-hunter-leather-bifold-wallet',
    description: 'Slimline pocket wallet crafted from oil-pullup hunter cowhide leather that ages with a rich patina. Features RFID blocking technology, 8 card slots, dual currency compartments, and an ID window.',
    category: 'Leather & Accessories',
    price: 2199,
    salePrice: 1699,
    stock: 45,
    sku: 'SHN-LTH-W04',
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    ],
    colors: ['Vintage Cognac', 'Classic Black', 'Espresso Dark Brown'],
    tags: ['Wallet', 'Leather', 'RFID Protection', 'Gift Box'],
    featured: false,
    isNew: false,
    isActive: true,
    specifications: {
      Material: '100% Genuine Top-Grain Oil Pull-up Leather',
      Security: 'Integrated RFID Shielding (13.56 MHz)',
      Capacity: '8 Card Slots, 2 Cash Dividers, 1 ID Window',
      Dimensions: '11.5 cm x 9.5 cm x 1.5 cm',
    },
  },
  {
    id: 'prod-005',
    name: 'ANC Pro Wireless Bluetooth 5.3 Earbuds (40Hr Playback)',
    slug: 'anc-pro-wireless-bluetooth-earbuds',
    description: 'Active Noise Cancellation with Environmental Noise Reduction (ENC) quad microphones for crystal-clear phone calls in traffic. Ultra-low 45ms gaming latency, IPX5 sweat resistance, and Type-C fast charge.',
    category: 'Electronics & Audio',
    price: 4999,
    salePrice: 3999,
    stock: 22,
    sku: 'SHN-ELC-E05',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800&auto=format&fit=crop&q=80',
    ],
    colors: ['Matte Black', 'Arctic White'],
    tags: ['Earbuds', 'ANC', 'Wireless', 'Fast Delivery'],
    featured: true,
    isNew: true,
    isActive: true,
    specifications: {
      Driver: '13mm Beryllium Dynamic Bass Drivers',
      Battery: '8 Hours Earbud + 32 Hours Storage Case (400mAh)',
      Charging: 'USB-C Fast Charging (10 mins gives 2 hours)',
      Bluetooth: 'v5.3 with AAC/SBC codec support',
    },
  },
  {
    id: 'prod-006',
    name: 'Women’s Chikankari Hand-Embroidered Kurti',
    slug: 'womens-chikankari-hand-embroidered-kurti',
    description: 'Delicate Lucknowi Chikankari jaal embroidery worked on pure sheer cotton cambric. Comes pre-washed with complementary cotton inner slip included. Perfect for university, work, and casual lunches.',
    category: "Women's Fashion",
    price: 3200,
    salePrice: 2650,
    stock: 16,
    sku: 'SHN-WMN-C06',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['Lilac Bloom', 'Powder Blue', 'Pearl White'],
    tags: ['Kurti', 'Chikankari', 'Handwork', 'Cotton'],
    featured: false,
    isNew: true,
    isActive: true,
    specifications: {
      Fabric: 'Pure Premium Cambric Cotton',
      Work: 'Authentic Traditional Chikankari Needlework',
      Inclusions: 'Free Cotton Inner Slip Included',
      Length: '38 Inches A-Line Cut',
    },
  },
  {
    id: 'prod-007',
    name: 'Executive Full-Grain Leather 15.6" Laptop Messenger Bag',
    slug: 'executive-leather-laptop-messenger-bag',
    description: 'Hand-tailored from thick full-grain cowhide leather with padded 15.6-inch laptop compartment, antique brass hardware, YKK zippers, and an adjustable padded shoulder strap designed for everyday commute.',
    category: 'Leather & Accessories',
    price: 7999,
    salePrice: 6499,
    stock: 12,
    sku: 'SHN-LTH-B07',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
    ],
    colors: ['Antique Tan', 'Dark Chocolate'],
    tags: ['Office', 'Laptop Bag', 'Leather', 'Executive'],
    featured: true,
    isNew: false,
    isActive: true,
    specifications: {
      Compartments: '1 Padded Laptop Sleeve (up to 15.6"), 2 Document Dividers, 3 Pen/Phone Pockets',
      Hardware: 'Heavy Solid Antique Brass with Reinforced Rivets',
      Straps: 'Detachable 52" Adjustable Shoulder Strap with Shoulder Pad',
      Warranty: '1-Year Leather Quality Guarantee',
    },
  },
  {
    id: 'prod-008',
    name: "Men's Supima Egyptian Cotton Formal Dress Shirt",
    slug: 'mens-supima-cotton-formal-dress-shirt',
    description: 'Wrinkle-resistant pinpoint oxford dress shirt tailored from 100% two-ply American Supima cotton. Features crisp spread collar, mother-of-pearl buttons, and rounded barrel cuffs.',
    category: "Men's Apparel",
    price: 3290,
    salePrice: 2590,
    stock: 28,
    sku: 'SHN-MEN-S08',
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['15 (S)', '15.5 (M)', '16 (L)', '16.5 (XL)'],
    colors: ['Sky Blue', 'Crisp White', 'Soft Pink Pinpoint'],
    tags: ['Formal', 'Cotton', 'Office Wear', 'Wrinkle Resistant'],
    featured: false,
    isNew: false,
    isActive: true,
    specifications: {
      Fabric: '100% 2-Ply Supima Long-Staple Cotton (120/2)',
      Collar: 'Fused Spread Semi-Cutaway Collar',
      Finish: 'Non-Iron Easy Care Easy Iron Technology',
    },
  },
  {
    id: 'prod-009',
    name: 'Handcrafted Multani Zari Work Khussa',
    slug: 'handcrafted-multani-zari-work-khussa',
    description: 'Authentic Multani bridal and festive flat khussa shoes adorned with radiant gold tilla zari thread embroidery, cushioned inner sole for zero shoe bites, and genuine leather sole.',
    category: 'Footwear & Chappal',
    price: 2490,
    salePrice: 1990,
    stock: 20,
    sku: 'SHN-FTW-K09',
    images: [
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['6 (36)', '7 (37)', '8 (38)', '9 (39)', '10 (40)'],
    colors: ['Royal Gold & Maroon', 'Silver Champagne', 'Black Velvet Zari'],
    tags: ['Khussa', 'Zari', 'Festive', 'Handmade'],
    featured: false,
    isNew: true,
    isActive: true,
    specifications: {
      Upper: 'Velvet Base with Hand-stitched Gold Tilla Zari',
      Sole: '100% Vegetable Tanned Buffalo Leather',
      Padding: 'Dual Layer Soft Foam Comfort Insole',
    },
  },
  {
    id: 'prod-010',
    name: 'Ultra AMOLED Health & Fitness Smartwatch with Calling',
    slug: 'ultra-amoled-health-fitness-smartwatch',
    description: '1.43-inch HD AMOLED display with Always-On screen, Bluetooth dual-mode telephone calling, SpO2 blood oxygen monitor, 120+ workout modes, and durable zinc-alloy unibody.',
    category: 'Electronics & Audio',
    price: 6499,
    salePrice: 4899,
    stock: 15,
    sku: 'SHN-ELC-W10',
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    ],
    colors: ['Titanium Grey', 'Obsidian Black', 'Military Green'],
    tags: ['Smartwatch', 'AMOLED', 'Bluetooth Calling', 'Gadget'],
    featured: true,
    isNew: true,
    isActive: true,
    specifications: {
      Display: '1.43" AMOLED 466x466 px 60Hz 1000 Nits Brightness',
      Compatibility: 'Android 6.0+ and iOS 11.0+',
      Battery: '380mAh (up to 7 days normal usage)',
      Waterproof: 'IP68 Swim & Rainproof',
    },
  },
];

export const initialCoupons: Coupon[] = [
  {
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    minimumOrder: 1500,
    maximumDiscount: 500,
    isActive: true,
  },
  {
    code: 'AZADI500',
    type: 'fixed',
    value: 500,
    minimumOrder: 4000,
    isActive: true,
  },
  {
    code: 'FIRSTBUY',
    type: 'percentage',
    value: 15,
    minimumOrder: 2500,
    maximumDiscount: 750,
    isActive: true,
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'banner-1',
    tag: '🔥 MEGA FESTIVE SALE 2026',
    headline: "Pakistan's Finest Handcrafted Footwear & Fashion",
    subheadline: 'Authentic Charsadda Peshawari Chappal, Luxury Lawn & Full-Grain Leather with nationwide doorstep Cash on Delivery.',
    badge: 'FLAT 25% OFF',
    offerCode: 'Use code "SHAAN10" for extra 10% off',
    bgImage: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'Shop Best Sellers',
    primaryLinkType: 'shop',
    primaryLinkValue: 'featured',
    secondaryBtnText: 'Explore Chappals',
    secondaryLinkType: 'category',
    secondaryLinkValue: 'footwear-chappal',
    accentColor: 'from-rose-600 to-amber-600',
    isActive: true,
    order: 1,
  },
  {
    id: 'banner-2',
    tag: '✨ NEW SEASON DROP',
    headline: 'Designer Unstitched Lawn & Festive Pret',
    subheadline: 'Intricate embroidery, lightweight breathable summer cotton, and vibrant colors crafted for timeless grace.',
    badge: 'NEW ARRIVALS',
    offerCode: 'Free Delivery on all orders above Rs. 3,000',
    bgImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: "Shop Women's Lawn",
    primaryLinkType: 'category',
    primaryLinkValue: 'womens-fashion',
    secondaryBtnText: 'View All Kurtas',
    secondaryLinkType: 'category',
    secondaryLinkValue: 'mens-apparel',
    accentColor: 'from-emerald-600 to-teal-700',
    isActive: true,
    order: 2,
  },
  {
    id: 'banner-3',
    tag: '🛡️ 100% GENUINE LEATHER',
    headline: 'Artisanal Wallets, Belts & Everyday Bags',
    subheadline: 'Pure cowhide leather hand-stitched by master artisans in Pakistan. Zero-fee payments via SBP Raast or Cash on Delivery.',
    badge: 'PREMIUM CRAFT',
    offerCode: 'Instant WhatsApp Order Support Available',
    bgImage: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1600&auto=format&fit=crop&q=80',
    primaryBtnText: 'Shop Leather Goods',
    primaryLinkType: 'category',
    primaryLinkValue: 'leather-accessories',
    secondaryBtnText: 'Order via WhatsApp',
    secondaryLinkType: 'whatsapp',
    secondaryLinkValue: '',
    accentColor: 'from-amber-600 to-stone-900',
    isActive: true,
    order: 3,
  },
];

